"""add authentication tables

Revision ID: 2235500bc159
Revises: 7a20ff0951f5
Create Date: 2026-06-25 14:35:34.422062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2235500bc159'
down_revision: Union[str, Sequence[str], None] = '7a20ff0951f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_records'))
    )
    op.create_index(op.f('ix_organization_records_slug'), 'organization_records', ['slug'], unique=True)
    op.create_table('user_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), server_default='owner', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization_records.id'], name=op.f('fk_user_records_organization_id_organization_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_records')),
    sa.UniqueConstraint('email', name='uq_user_records_email')
    )
    op.create_index(op.f('ix_user_records_email'), 'user_records', ['email'], unique=False)
    op.create_index(op.f('ix_user_records_organization_id'), 'user_records', ['organization_id'], unique=False)
    op.create_table('refresh_token_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('token_id', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization_records.id'], name=op.f('fk_refresh_token_records_organization_id_organization_records'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_records.id'], name=op.f('fk_refresh_token_records_user_id_user_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_token_records'))
    )
    op.create_index(op.f('ix_refresh_token_records_expires_at'), 'refresh_token_records', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_token_records_organization_id'), 'refresh_token_records', ['organization_id'], unique=False)
    op.create_index(op.f('ix_refresh_token_records_revoked_at'), 'refresh_token_records', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_refresh_token_records_token_hash'), 'refresh_token_records', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_token_records_token_id'), 'refresh_token_records', ['token_id'], unique=True)
    op.create_index(op.f('ix_refresh_token_records_user_id'), 'refresh_token_records', ['user_id'], unique=False)
    op.alter_column('document_chunk_records', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('document_records', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('document_records', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###
    op.execute(
        sa.text(
            """
            INSERT INTO
                organization_membership_records
            (
                id,
                organization_id,
                user_id,
                role,
                is_active,
                created_at,
                updated_at
            )
            SELECT
                UUID(),
                user_records.organization_id,
                user_records.id,
                user_records.role,
                user_records.is_active,
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            FROM user_records
            WHERE NOT EXISTS
            (
                SELECT 1
                FROM organization_membership_records
                WHERE
                    organization_membership_records
                        .organization_id
                        = user_records.organization_id
                    AND organization_membership_records
                        .user_id
                        = user_records.id
            )
            """
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_records', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('document_records', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('document_chunk_records', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_index(op.f('ix_refresh_token_records_user_id'), table_name='refresh_token_records')
    op.drop_index(op.f('ix_refresh_token_records_token_id'), table_name='refresh_token_records')
    op.drop_index(op.f('ix_refresh_token_records_token_hash'), table_name='refresh_token_records')
    op.drop_index(op.f('ix_refresh_token_records_revoked_at'), table_name='refresh_token_records')
    op.drop_index(op.f('ix_refresh_token_records_organization_id'), table_name='refresh_token_records')
    op.drop_index(op.f('ix_refresh_token_records_expires_at'), table_name='refresh_token_records')
    op.drop_table('refresh_token_records')
    op.drop_index(op.f('ix_user_records_organization_id'), table_name='user_records')
    op.drop_index(op.f('ix_user_records_email'), table_name='user_records')
    op.drop_table('user_records')
    op.drop_index(op.f('ix_organization_records_slug'), table_name='organization_records')
    op.drop_table('organization_records')
    # ### end Alembic commands ###
