"""add organization memberships

Revision ID: 3b272a9c9495
Revises: 2235500bc159
Create Date: 2026-06-26 13:05:20.637126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3b272a9c9495'
down_revision: Union[str, Sequence[str], None] = '2235500bc159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_membership_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), server_default='member', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization_records.id'], name=op.f('fk_organization_membership_records_organization_id_organization_records'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_records.id'], name=op.f('fk_organization_membership_records_user_id_user_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_membership_records')),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_organization_membership_organization_user')
    )
    op.create_index(op.f('ix_organization_membership_records_is_active'), 'organization_membership_records', ['is_active'], unique=False)
    op.create_index(op.f('ix_organization_membership_records_organization_id'), 'organization_membership_records', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_membership_records_role'), 'organization_membership_records', ['role'], unique=False)
    op.create_index(op.f('ix_organization_membership_records_user_id'), 'organization_membership_records', ['user_id'], unique=False)
    op.alter_column('document_chunk_records', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('document_records', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('document_records', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('organization_records', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('refresh_token_records', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('user_records', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('user_records', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_records', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('user_records', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('refresh_token_records', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('organization_records', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('document_records', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('document_records', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('document_chunk_records', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_index(op.f('ix_organization_membership_records_user_id'), table_name='organization_membership_records')
    op.drop_index(op.f('ix_organization_membership_records_role'), table_name='organization_membership_records')
    op.drop_index(op.f('ix_organization_membership_records_organization_id'), table_name='organization_membership_records')
    op.drop_index(op.f('ix_organization_membership_records_is_active'), table_name='organization_membership_records')
    op.drop_table('organization_membership_records')
    # ### end Alembic commands ###
